apiVersion: apps/v1 
kind: Deployment
metadata:
  name: jeffsbooks
  namespace: jeffsbooks
  labels:
    app: jeffsbooks
spec:
  selector:
    matchLabels:
      app: jeffsbooks
  template:
    metadata:
      labels:
        app: jeffsbooks
    spec:
      imagePullSecrets:
        - name: dockerhub
      containers:
        - image: jeffthorne/books:latest
          name: jeffsbooks
          imagePullPolicy: Always
          env:
            - name: POSTGRES_HOST
              value: 10.72.6.150
            - name: FLASK_ENV
              value: production
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8088
              name: flask

