apiVersion: apps/v1 
kind: Deployment
metadata:
  name: jeffsbooks
  namespace: jeffsbooks
  labels:
    app: jeffsbooks
spec:
  selector:
    matchLabels:
      app: jeffsbooks
  template:
    metadata:
      labels:
        app: jeffsbooks
    spec:
      containers:
        - image: jeffthorne/books:latest
          name: jeffsbooks
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
              name: flask